---
- hosts: "{{ HOSTS }}"
  become: yes
  gather_facts: False
  vars:
    report_server: node1
  
  tasks:
  - wait_for_connection:
  - dnf:
      name: python36
    ignore_errors: True
    
  - include_role:
      name: demo.patching.patch_linux

  - block:
    - yum:
        name: httpd
        state: latest
      check_mode: no

    - file:
        path: /var/www/html/reports/
        state: directory
      check_mode: no

    - copy:
        dest: /var/www/html/reports/.htaccess
        content: Options +Indexes
      check_mode: no

    - service:
        name: httpd
        state: started
      check_mode: no

    - include_role:
        name: demo.patching.report_linux

    - include_role:
        name: demo.patching.report_linux_patching
    delegate_to: "{{ report_server }}"
    run_once: yes
